"""
Email Agent — Outlook COM automation with SMTP fallback.

Capabilities:
- Draft and send emails via Outlook
- Attach files (Word, Excel, PDF)
- Generate email body using LLM
- Save to Drafts or send with approval
- SMTP fallback when Outlook is unavailable
"""
from __future__ import annotations

import os
import smtplib
import sys
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any, Dict, List, Optional

from agents.base_agent import BaseAgent
from models.schemas import AgentType, RiskLevel
from services.llm_service import get_llm_service
from utils.logger import get_logger

logger = get_logger("agents.email", "email")

_COM_AVAILABLE = False
_OUTLOOK_INSTALLED = False

if sys.platform == "win32":
    try:
        import win32com.client as win32
        import pythoncom
        _COM_AVAILABLE = True
        # Check if Outlook is actually registered before trying COM
        try:
            import winreg
            winreg.OpenKey(winreg.HKEY_CLASSES_ROOT, "Outlook.Application")
            _OUTLOOK_INSTALLED = True
        except (ImportError, FileNotFoundError, OSError):
            logger.warning("Outlook not installed — using SMTP fallback for all email operations")
    except ImportError:
        logger.warning("pywin32 not available — SMTP fallback only")


def _normalize_address(value) -> str:
    """Convert list or string email address(es) to a single comma-separated string."""
    if not value:
        return ""
    if isinstance(value, list):
        return ", ".join(str(v) for v in value if v)
    return str(value).strip()


class EmailAgent(BaseAgent):
    """Drafts and sends emails via Outlook COM or SMTP."""

    def __init__(self):
        self._outlook = None
        self._drafts: Dict[str, Any] = {}  # draft_id -> mail item or smtp dict
        self.llm = get_llm_service()
        # Only use COM if Outlook is confirmed installed
        self._use_com = (_COM_AVAILABLE and _OUTLOOK_INSTALLED
                         and os.getenv("DEMO_MODE", "false").lower() != "true")
        super().__init__(AgentType.EMAIL)

    def _register_tools(self):
        self.register_tool(
            "email.create_draft", self.create_draft,
            "Create an email draft",
            required_args=["to", "subject", "body"],
            risk_level=RiskLevel.MEDIUM,
        )
        self.register_tool(
            "email.send_draft", self.send_draft,
            "Send a saved email draft",
            required_args=["draft_id"],
            risk_level=RiskLevel.HIGH,
        )
        self.register_tool(
            "email.save_to_drafts", self.save_to_drafts,
            "Save draft to Outlook Drafts folder",
            required_args=["draft_id"],
        )
        self.register_tool(
            "email.add_attachment", self.add_attachment,
            "Add a file attachment to a draft",
            required_args=["draft_id", "file_path"],
        )
        self.register_tool(
            "email.generate_body", self.generate_body,
            "Generate email body text using LLM",
            required_args=["subject", "key_points"],
        )
        self.register_tool(
            "email.list_drafts", self.list_drafts,
            "List all current drafts",
        )

    # ─────────────────────────────────────────
    # Draft Creation
    # ─────────────────────────────────────────

    def create_draft(
        self,
        to,
        subject: str,
        body: str,
        cc=None,
        bcc=None,
        attachments: List[str] = None,
        html_body: bool = False,
    ) -> Dict[str, Any]:
        """Create an email draft. Normalizes to/cc/bcc to handle list or string input."""
        # Normalize addresses — LLM sometimes sends lists instead of strings
        to  = _normalize_address(to)
        cc  = _normalize_address(cc)
        bcc = _normalize_address(bcc)
        attachments = attachments or []

        # Resolve template body generated by LLM placeholder
        if isinstance(body, str) and body.startswith("{{llm:") and body.endswith("}}"):
            instructions = body[6:-2].strip()
            body = self.generate_body(subject=subject, key_points=instructions)["body"]

        if self._use_com:
            return self._create_draft_com(to, subject, body, cc, bcc, attachments, html_body)
        else:
            return self._create_draft_smtp(to, subject, body, cc, bcc, attachments)

    def _create_draft_com(self, to, subject, body, cc, bcc, attachments, html_body) -> Dict:
        """Create draft via Outlook COM."""
        try:
            pythoncom.CoInitialize()
            self._outlook = win32.Dispatch("Outlook.Application")
            mail = self._outlook.CreateItem(0)  # olMailItem = 0

            mail.To = to if isinstance(to, str) else "; ".join(to)
            mail.CC = cc
            mail.BCC = bcc
            mail.Subject = subject

            if html_body:
                mail.HTMLBody = body
            else:
                mail.Body = body

            for att_path in attachments:
                att_resolved = str(Path(att_path).expanduser().resolve())
                if Path(att_resolved).exists():
                    mail.Attachments.Add(att_resolved)
                else:
                    logger.warning(f"Attachment not found: {att_resolved}")

            draft_id = f"draft_{len(self._drafts) + 1}"
            self._drafts[draft_id] = mail

            logger.info(f"Draft created via COM: to={to}, subject={subject}")
            return {
                "draft_id": draft_id,
                "to": to,
                "subject": subject,
                "method": "com",
                "attachments": attachments,
                "status": "draft_ready",
            }
        except Exception as e:
            logger.warning(f"COM draft failed ({e}), using SMTP fallback")
            return self._create_draft_smtp(to, subject, body, cc, bcc, attachments)

    def _create_draft_smtp(self, to, subject, body, cc, bcc, attachments) -> Dict:
        """Create draft dict for SMTP sending. Always normalizes addresses to strings."""
        # Normalize here too — this method may be called directly from COM fallback
        # before create_draft's normalization has run
        to_str  = _normalize_address(to)
        cc_str  = _normalize_address(cc)
        bcc_str = _normalize_address(bcc)

        draft_id = f"smtp_draft_{len(self._drafts) + 1}"
        self._drafts[draft_id] = {
            "to":          to_str,
            "subject":     str(subject) if subject else "",
            "body":        str(body)    if body    else "",
            "cc":          cc_str,
            "bcc":         bcc_str,
            "attachments": [str(p) for p in (attachments or [])],
            "method":      "smtp",
        }
        logger.info(f"SMTP draft created: {draft_id} → to={to_str}")
        return {
            "draft_id": draft_id,
            "to":       to_str,
            "subject":  str(subject) if subject else "",
            "method":   "smtp",
            "attachments": attachments or [],
            "status":   "draft_ready",
        }

    # ─────────────────────────────────────────
    # Send / Save
    # ─────────────────────────────────────────

    def send_draft(self, draft_id: str) -> Dict[str, Any]:
        """Send a previously created draft. Requires prior approval."""
        draft = self._drafts.get(draft_id)
        if draft is None:
            raise ValueError(f"Draft not found: {draft_id}")

        if isinstance(draft, dict):
            # SMTP send
            return self._send_smtp(draft_id, draft)
        else:
            # COM send
            try:
                draft.Send()
                del self._drafts[draft_id]
                logger.info(f"Email sent via COM: {draft_id}")
                return {"sent": True, "draft_id": draft_id, "method": "com"}
            except Exception as e:
                logger.error(f"COM send failed: {e}")
                raise

    def _send_smtp(self, draft_id: str, draft: Dict) -> Dict:
        """Send email via SMTP."""
        smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
        smtp_port = int(os.getenv("SMTP_PORT", "587"))
        smtp_user = os.getenv("SMTP_USER", "")
        smtp_pass = os.getenv("SMTP_PASSWORD", "")

        if not smtp_user or not smtp_pass:
            raise RuntimeError(
                "SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD in .env"
            )

        # Normalize all address fields to strings
        to_str  = _normalize_address(draft.get("to", ""))
        cc_str  = _normalize_address(draft.get("cc", ""))
        bcc_str = _normalize_address(draft.get("bcc", ""))

        msg = MIMEMultipart()
        msg["From"]    = smtp_user
        msg["To"]      = to_str
        msg["Subject"] = draft["subject"]
        if cc_str:
            msg["CC"] = cc_str
        msg.attach(MIMEText(draft.get("body", ""), "plain"))

        logger.info(f"Sending via SMTP: To={to_str} CC={cc_str or '—'} Subject={draft['subject']}")

        for att_path in draft.get("attachments", []):
            att_path = str(Path(att_path).expanduser().resolve())
            if Path(att_path).exists():
                with open(att_path, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={Path(att_path).name}",
                )
                msg.attach(part)

        use_tls = os.getenv("SMTP_USE_TLS", "true").lower() == "true"
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            if use_tls:
                server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)

        del self._drafts[draft_id]
        logger.info(f"Email sent via SMTP: {draft_id}")
        return {"sent": True, "draft_id": draft_id, "method": "smtp"}

    def save_to_drafts(self, draft_id: str) -> Dict[str, Any]:
        """Save draft to Outlook Drafts folder without sending."""
        draft = self._drafts.get(draft_id)
        if draft is None:
            raise ValueError(f"Draft not found: {draft_id}")

        if isinstance(draft, dict):
            # Can't save SMTP draft to Outlook — just keep in memory
            return {"saved": True, "location": "in_memory", "draft_id": draft_id}

        try:
            draft.Save()
            logger.info(f"Draft saved to Outlook Drafts: {draft_id}")
            return {"saved": True, "location": "outlook_drafts", "draft_id": draft_id}
        except Exception as e:
            logger.error(f"Save to drafts failed: {e}")
            raise

    def add_attachment(self, draft_id: str, file_path: str) -> Dict[str, Any]:
        """Add a file attachment to an existing draft."""
        draft = self._drafts.get(draft_id)
        if draft is None:
            raise ValueError(f"Draft not found: {draft_id}")

        resolved = str(Path(file_path).expanduser().resolve())
        if not Path(resolved).exists():
            raise FileNotFoundError(f"Attachment file not found: {resolved}")

        if isinstance(draft, dict):
            draft["attachments"].append(resolved)
        else:
            draft.Attachments.Add(resolved)
            self._drafts[draft_id] = draft

        logger.info(f"Attachment added to {draft_id}: {Path(resolved).name}")
        return {"added": True, "file": resolved, "draft_id": draft_id}

    def list_drafts(self) -> Dict[str, Any]:
        """List all current drafts."""
        drafts_info = []
        for draft_id, draft in self._drafts.items():
            if isinstance(draft, dict):
                info = {
                    "id": draft_id,
                    "to": draft.get("to"),
                    "subject": draft.get("subject"),
                    "method": "smtp",
                    "attachments": len(draft.get("attachments", [])),
                }
            else:
                try:
                    info = {
                        "id": draft_id,
                        "to": draft.To,
                        "subject": draft.Subject,
                        "method": "com",
                        "attachments": draft.Attachments.Count,
                    }
                except Exception:
                    info = {"id": draft_id, "method": "com", "error": "Could not read draft"}
            drafts_info.append(info)
        return {"drafts": drafts_info, "count": len(drafts_info)}

    # ─────────────────────────────────────────
    # LLM Body Generation
    # ─────────────────────────────────────────

    def generate_body(
        self,
        subject: str,
        key_points: str,
        tone: str = "professional",
        recipient_context: str = "",
    ) -> Dict[str, Any]:
        """Use Grok to generate a professional email body."""
        from prompts.agent_prompts import EMAIL_DRAFT_PROMPT
        prompt = EMAIL_DRAFT_PROMPT.format(
            recipient_context=recipient_context or "a business colleague",
            subject=subject,
            key_points=key_points,
            tone=tone,
            attachments="the attached file" if key_points else "none",
        )
        body = self.llm.generate_text(prompt)
        return {"body": body, "generated": True}

    def __del__(self):
        try:
            if self._outlook:
                self._outlook = None
        except Exception:
            pass
