"""
Core Pydantic schemas for the Desktop Automation Agent.
All inter-component data flows through these strongly-typed models.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────
# Enumerations
# ─────────────────────────────────────────────

class ExecutionMode(str, Enum):
    SAFE      = "safe"        # Confirm before every risky action
    SEMI_AUTO = "semi_auto"   # Confirm only for email/delete
    DEMO      = "demo"        # No confirmations except sending email
    DRY_RUN   = "dry_run"     # Simulate only — no real OS actions


class AgentType(str, Enum):
    PLANNER       = "planner"
    EXCEL         = "excel"
    WORD          = "word"
    EMAIL         = "email"
    FILE          = "file"
    UI_AUTOMATION = "ui_automation"
    ORCHESTRATOR  = "orchestrator"
    MEMORY        = "memory"


class StepStatus(str, Enum):
    PENDING   = "pending"
    RUNNING   = "running"
    SUCCESS   = "success"
    FAILED    = "failed"
    SKIPPED   = "skipped"
    WAITING   = "waiting_approval"
    CANCELLED = "cancelled"


class MessageRole(str, Enum):
    USER      = "user"
    ASSISTANT = "assistant"
    SYSTEM    = "system"
    TOOL      = "tool"


class ArtifactType(str, Enum):
    EXCEL = "excel"
    WORD  = "word"
    PDF   = "pdf"
    CSV   = "csv"
    IMAGE = "image"
    TEXT  = "text"
    OTHER = "other"


class RiskLevel(str, Enum):
    LOW    = "low"
    MEDIUM = "medium"
    HIGH   = "high"


# ─────────────────────────────────────────────
# Core Request / Response Models
# ─────────────────────────────────────────────

class UserRequest(BaseModel):
    """Represents a raw request from the user."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    text: str
    attachments: List[str] = Field(default_factory=list)  # file paths
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    execution_mode: ExecutionMode = ExecutionMode.SAFE


class ToolCall(BaseModel):
    """A single tool invocation with its parameters."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    tool_name: str                    # e.g. "excel.read_sheet"
    agent: AgentType
    arguments: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    risk_level: RiskLevel = RiskLevel.LOW
    requires_approval: bool = False


class ToolResult(BaseModel):
    """The structured result from a tool execution."""
    tool_call_id: str
    tool_name: str
    success: bool
    data: Any = None                  # Return payload
    error: Optional[str] = None
    duration_ms: Optional[float] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    screenshot_path: Optional[str] = None  # Captured on failure


class PlanStep(BaseModel):
    """A single step within an execution plan."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    order: int
    title: str
    description: str
    agent: AgentType
    tool_calls: List[ToolCall] = Field(default_factory=list)
    dependencies: List[str] = Field(default_factory=list)  # step ids
    status: StepStatus = StepStatus.PENDING
    result: Optional[ToolResult] = None
    error: Optional[str] = None
    requires_approval: bool = False
    approval_message: Optional[str] = None
    risk_level: RiskLevel = RiskLevel.LOW
    fallback_strategy: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    @property
    def duration_seconds(self) -> Optional[float]:
        if self.started_at and self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None


class ExecutionPlan(BaseModel):
    """The full structured plan generated by the Planner Agent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    request_id: str
    session_id: str
    intent_summary: str
    steps: List[PlanStep]
    required_agents: List[AgentType]
    estimated_duration_seconds: Optional[int] = None
    missing_info: List[str] = Field(default_factory=list)  # Questions to ask
    clarification_needed: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)
    raw_llm_response: Optional[str] = None

    @property
    def total_steps(self) -> int:
        return len(self.steps)

    @property
    def completed_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == StepStatus.SUCCESS)

    @property
    def progress_pct(self) -> float:
        if not self.steps:
            return 0.0
        return (self.completed_steps / self.total_steps) * 100


class AgentResult(BaseModel):
    """Result returned by any agent after executing a step."""
    step_id: str
    agent: AgentType
    success: bool
    output: Any = None
    artifacts: List["Artifact"] = Field(default_factory=list)
    error: Optional[str] = None
    tool_results: List[ToolResult] = Field(default_factory=list)
    logs: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Artifact(BaseModel):
    """A file or data artifact produced during execution."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    path: str
    artifact_type: ArtifactType
    size_bytes: Optional[int] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    description: Optional[str] = None
    step_id: Optional[str] = None
    session_id: Optional[str] = None

    @property
    def extension(self) -> str:
        return self.path.rsplit(".", 1)[-1].lower() if "." in self.path else ""


class ApprovalRequest(BaseModel):
    """Sent to the UI when an action needs user approval."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    step_id: str
    title: str
    description: str
    action_summary: str
    risk_level: RiskLevel
    details: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    approved: Optional[bool] = None
    response_time: Optional[datetime] = None


class Message(BaseModel):
    """A single message in the conversation."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    role: MessageRole
    content: str
    attachments: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    plan_id: Optional[str] = None
    tool_calls: List[ToolCall] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ErrorReport(BaseModel):
    """Structured error for display and logging."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    step_id: Optional[str] = None
    agent: Optional[AgentType] = None
    tool_name: Optional[str] = None
    error_type: str
    message: str
    traceback: Optional[str] = None
    recovery_suggestion: Optional[str] = None
    screenshot_path: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class SessionState(BaseModel):
    """Full state of an automation session."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = "New Session"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    messages: List[Message] = Field(default_factory=list)
    plans: List[ExecutionPlan] = Field(default_factory=list)
    artifacts: List[Artifact] = Field(default_factory=list)
    errors: List[ErrorReport] = Field(default_factory=list)
    execution_mode: ExecutionMode = ExecutionMode.SAFE
    context: Dict[str, Any] = Field(default_factory=dict)  # Shared memory
    active_plan_id: Optional[str] = None

    @property
    def active_plan(self) -> Optional[ExecutionPlan]:
        if self.active_plan_id:
            return next((p for p in self.plans if p.id == self.active_plan_id), None)
        return None


class LLMMessage(BaseModel):
    """Message format for LLM API calls."""
    role: str  # "system" | "user" | "assistant"
    content: str


class LLMRequest(BaseModel):
    """Request to the LLM service."""
    messages: List[LLMMessage]
    model: Optional[str] = None
    max_tokens: int = 4096
    temperature: float = 0.2
    response_format: Optional[Dict[str, str]] = None  # {"type": "json_object"}


class LLMResponse(BaseModel):
    """Response from the LLM service."""
    content: str
    model: str
    input_tokens: int = 0
    output_tokens: int = 0
    duration_ms: float = 0.0
    raw: Optional[Dict[str, Any]] = None


# Allow forward refs
AgentResult.model_rebuild()
